# Generated by Django 5.2.14 on 2026-05-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('donante', 'Donante'), ('beneficiario', 'Beneficiario'), ('admin', 'Administrador'), ('voluntario', 'Voluntario')], default='donante', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuentas',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('foto_url', models.URLField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Gobernanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('img_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Miembro de Gobernanza',
                'verbose_name_plural': 'Miembros de Gobernanza',
                'db_table': 'gobernanza',
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(default='logro', max_length=50)),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'db_table': 'hitos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(default='PDF', max_length=10)),
                ('size', models.CharField(blank=True, default='', max_length=10)),
                ('archivo_url', models.URLField(blank=True, default='')),
                ('icono', models.CharField(default='bi-file-earmark-pdf-fill', max_length=50)),
                ('color', models.CharField(default='#DD4444', max_length=7)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recurso',
                'db_table': 'tipos_recurso',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
                'db_table': 'valores',
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(default='Metropolitana', max_length=50)),
                ('direccion', models.TextField()),
                ('comuna', models.CharField(blank=True, default='', max_length=50)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacidad', models.IntegerField(default=0)),
                ('inventario', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Capacidad crítica', 'Capacidad crítica'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros', to='gateway.cuenta')),
            ],
            options={
                'verbose_name': 'Centro de Acopio',
                'verbose_name_plural': 'Centros de Acopio',
                'db_table': 'centros',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('origen_display', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('En acopio', 'En acopio'), ('En tránsito', 'En tránsito'), ('Recibida', 'Recibida'), ('Entregado', 'Entregado'), ('Distribuida', 'Distribuida'), ('Cancelada', 'Cancelada')], default='En acopio', max_length=20)),
                ('comprobante', models.CharField(blank=True, default='', max_length=100)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donaciones', to='gateway.centro')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donaciones_origen', to='gateway.cuenta')),
                ('tipo_recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gateway.tiporecurso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gateway.unidad')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('destino', models.CharField(max_length=300)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente despacho', 'Pendiente despacho'), ('En tránsito', 'En tránsito'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente despacho', max_length=20)),
                ('transportista', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='gateway.centro')),
                ('donacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='gateway.donacion')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envios',
            },
        ),
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('urgencia', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('Cubierto', 'Cubierto'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('reportado_por', models.CharField(blank=True, default='', max_length=200)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necesidades', to='gateway.centro')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necesidades_creadas', to='gateway.cuenta')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gateway.tiporecurso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gateway.unidad')),
            ],
            options={
                'verbose_name': 'Necesidad',
                'verbose_name_plural': 'Necesidades',
                'db_table': 'necesidades',
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('necesidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='gateway.necesidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to='gateway.cuenta')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'db_table': 'propuestas',
            },
        ),
        migrations.CreateModel(
            name='UnidadPorTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_permitidas', to='gateway.tiporecurso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.unidad')),
            ],
            options={
                'db_table': 'unidades_por_tipo',
                'unique_together': {('tipo_recurso', 'unidad')},
            },
        ),
    ]
