# Generated by Django 5.2.14 on 2026-05-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('donante', 'Donante'), ('beneficiario', 'Beneficiario'), ('admin', 'Administrador'), ('voluntario', 'Voluntario')], default='donante', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuentas',
            },
        ),
    ]
