# Generated by Django 5.2.14 on 2026-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_acopio_id', models.PositiveIntegerField(help_text='Enlace lógico al microservicio de Logística', verbose_name='ID del Centro de Acopio destino')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título corto (ej: Pañales para niños)')),
                ('descripcion', models.TextField(verbose_name='Detalle de la urgencia o requerimiento')),
                ('categoria', models.CharField(choices=[('ALIMENTOS', 'Alimentos y Víveres'), ('ROPA', 'Ropa y Abrigo'), ('DINERO', 'Aporte Económico'), ('SALUD', 'Insumos Médicos'), ('UTILES', 'Útiles de Aseo / Limpieza'), ('VOLUNTARIADO', 'Voluntariado / Mano de Obra'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('APROBADA', 'Activa / Buscando Donaciones'), ('EN_PROCESO', 'En Camino / Asignada'), ('CUBIERTA', 'Meta Alcanzada / Finalizada'), ('RECHAZADA', 'Rechazada / Cancelada'), ('Activa', 'Activa'), ('Pendiente', 'Pendiente'), ('Cubierto', 'Cubierto')], default='Pendiente', max_length=20)),
                ('urgencia', models.CharField(blank=True, choices=[('', 'Pendiente de asignación'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='', max_length=10)),
                ('cantidad_requerida', models.PositiveIntegerField(default=1, verbose_name='Cantidad Total Necesitada')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida Actual')),
                ('unidad_medida', models.CharField(default='unidades', help_text='ej: kg, litros, cajas, unidades', max_length=30)),
                ('solicitante_nombre', models.CharField(max_length=100, verbose_name='Nombre de quien solicita / Organización')),
                ('solicitante_contacto', models.CharField(blank=True, default='', max_length=150, verbose_name='Contacto (Teléfono o Email)')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales (urgencia original, etc.)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Necesidad',
                'verbose_name_plural': 'Necesidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
