# Generated by Django 5.2.14 on 2026-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_necesidades', '0003_estadonecesidad_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='necesidad',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de la necesidad'),
        ),
        migrations.AlterField(
            model_name='estadonecesidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Detalle de la urgencia o requerimiento'),
        ),
    ]
