# Generated by Django 5.2.15 on 2026-06-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('idCentro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('direccion', models.CharField(default='', max_length=255)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('encargado', models.CharField(default='', max_length=100)),
                ('capacidadTotal', models.IntegerField()),
                ('capacidadUsada', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('inventario', models.JSONField(default=list)),
            ],
        ),
    ]
