# Generated by Django 5.2.16 on 2026-07-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('disponibilidad', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('fines_semana', 'Fines de semana'), ('emergencia', 'Solo emergencias')], default='emergencia', max_length=20)),
                ('habilidades', models.JSONField(blank=True, default=list, verbose_name='Habilidades')),
                ('centro_preferido', models.CharField(blank=True, default='', help_text='ID lógico del centro en el microservicio de Logística', max_length=50, verbose_name='Centro de acopio preferido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField(verbose_name='Horas trabajadas')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('registrado_por_rut', models.CharField(max_length=12, verbose_name='RUT de quien registró')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to='api_voluntarios.voluntario', verbose_name='Voluntario')),
            ],
            options={
                'verbose_name': 'Registro de horas',
                'verbose_name_plural': 'Registros de horas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesidad_id', models.PositiveIntegerField(help_text='Enlace lógico al microservicio de Necesidades', verbose_name='ID de la necesidad')),
                ('estado', models.CharField(choices=[('propuesto', 'Propuesto'), ('asignado', 'Asignado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='propuesto', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api_voluntarios.voluntario', verbose_name='Voluntario')),
            ],
            options={
                'verbose_name': 'Asignación de voluntario',
                'verbose_name_plural': 'Asignaciones de voluntarios',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('voluntario', 'necesidad_id')},
            },
        ),
    ]
