# Generated by Django 5.2.14 on 2026-07-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_servicio', '0004_logro_logrousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='centro_acopio_id',
            field=models.CharField(blank=True, help_text='ID del centro de acopio asignado (solo para rol encargado)', max_length=50, null=True),
        ),
    ]
