# Generated by Django 5.2.15 on 2026-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('idDonacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('origen', models.CharField(max_length=150)),
                ('centroId', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('detalles', models.JSONField(default=dict)),
            ],
        ),
    ]
