# Generated by Django 5.2.14 on 2026-07-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_donaciones', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='unidad',
            field=models.CharField(blank=True, default='kg', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ItemDonacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('detalles', models.JSONField(default=dict)),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_donaciones.donacion')),
            ],
        ),
    ]
