# Generated by Django 5.2.14 on 2026-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_donaciones', '0005_estadodonacion_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdonacion',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
